
/**************************************************************
 *	
 *	GameSound, 8 bit, 11025Hz,
 *	1 channel, 483115 bytes/channel
 *	Total Size: 1 * 483115 + 4 (header) = 483159 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anjana Balamourougan\Documents\Georgia Tech\CS 2261\Final Project\M04_AnjanaBalamourougan\GameSound.aiff
 *	Time-stamp: Sun Dec 11 12:51:47 2016
 *	
 **************************************************************/

#ifndef __GAMESOUNDH__
#define __GAMESOUNDH__

#define GAMESOUNDFREQ 11025
#define GAMESOUNDLEN 483115

extern const unsigned char GameSound[483115];

#endif /* __GAMESOUNDH__ */
