
/**************************************************************
 *	
 *	HoneyPotSound, 8 bit, 11025Hz,
 *	1 channel, 11758 bytes/channel
 *	Total Size: 1 * 11758 + 4 (header) = 11802 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anjana Balamourougan\Documents\Georgia Tech\CS 2261\Final Project\M04_AnjanaBalamourougan\HoneyPotSound.aiff
 *	Time-stamp: Mon Dec 05 23:38:38 2016
 *	
 **************************************************************/

#ifndef __HONEYPOTSOUNDH__
#define __HONEYPOTSOUNDH__

#define HONEYPOTSOUNDFREQ 11025
#define HONEYPOTSOUNDLEN 11758

extern const unsigned char HoneyPotSound[11758];

#endif /* __HONEYPOTSOUNDH__ */
