
/**************************************************************
 *	
 *	LoseSound, 8 bit, 11025Hz,
 *	1 channel, 13035 bytes/channel
 *	Total Size: 1 * 13035 + 4 (header) = 13079 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anjana Balamourougan\Documents\Georgia Tech\CS 2261\Final Project\M04_AnjanaBalamourougan\LoseSound.aiff
 *	Time-stamp: Sun Dec 11 13:26:43 2016
 *	
 **************************************************************/

#ifndef __LOSESOUNDH__
#define __LOSESOUNDH__

#define LOSESOUNDFREQ 11025
#define LOSESOUNDLEN 13035

extern const unsigned char LoseSound[13035];

#endif /* __LOSESOUNDH__ */
