
/**************************************************************
 *	
 *	WinnieTitleSong, 8 bit, 11025Hz,
 *	1 channel, 561460 bytes/channel
 *	Total Size: 1 * 561460 + 4 (header) = 561504 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anjana Balamourougan\Documents\Georgia Tech\CS 2261\Final Project\M04_AnjanaBalamourougan\WinnieTitleSong.aiff
 *	Time-stamp: Sun Dec 11 12:53:17 2016
 *	
 **************************************************************/

#ifndef __WINNIETITLESONGH__
#define __WINNIETITLESONGH__

#define WINNIETITLESONGFREQ 11025
#define WINNIETITLESONGLEN 561460

extern const unsigned char WinnieTitleSong[561460];

#endif /* __WINNIETITLESONGH__ */
