
/**************************************************************
 *	
 *	WinSound, 8 bit, 11025Hz,
 *	1 channel, 18202 bytes/channel
 *	Total Size: 1 * 18202 + 4 (header) = 18246 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Anjana Balamourougan\Documents\Georgia Tech\CS 2261\Final Project\M04_AnjanaBalamourougan\WinSound.aiff
 *	Time-stamp: Sun Dec 11 13:26:29 2016
 *	
 **************************************************************/

#ifndef __WINSOUNDH__
#define __WINSOUNDH__

#define WINSOUNDFREQ 11025
#define WINSOUNDLEN 18202

extern const unsigned char WinSound[18202];

#endif /* __WINSOUNDH__ */
